blank_issues_enabled: false
contact_links:
  - name: â“ Questions
    url: https://github.com/RapidAI/RapidOCRPDF/discussions/categories/q-a
    about: Please use the community forum for help and questions regarding LabelConvert Docs.
  - name: ğŸ’¡ Ideas
    url: https://github.com/RapidAI/RapidOCRPDF/discussions/categories/ideas
    about: Please vote for and post new feature ideas in the community forum.